apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ns-dig
  namespace: cluster-tools
spec:
  encryptedData:
    rfc2136_tsig_secret: AgAFmxm0f8SBxItrDLW+a3hMohFm2Juftx4jUJWiBIAm5lp34jLoKHp7MbW3NDF10ZgISC6Hg0Bv/qMhHMiXnjfnoAI0Y9Bw+UFjZUuZ/wvQ7EbHZRHv+xkRyPDOqPjiMlFwrBcrHx2f6WEu6f1V5W1ewk4j17uUmF9QV7U/c0xddkp2xNan+v/QU/YjTOwRH9skfJFcqIF70sJ5dLAmy1aV6qGYIggDnjPSvr7+HeUTPZ8/rt91a8l6awLK8dm3Qc1ZJlM1LGo0ewQQZqK5VDGDM91CvYsRmq4XCWk7DzW445lZ9yaHkU06QALR4r85IaR60ceXaAgewKx/MBL4mEJlZ8y7u7QYkwP0rQIeoOm6tmwmcqHVljfYYaKMj6QEzdzJpikJ23WMs+XiQn5kEMsAWGrzZT8Xz8JLjYemuRteBqLIc24ELNCnLSmbx70+I+QnfuAXfh/tueKbnS8vKYzwZyk8Bz1tPwoV1YUkYHxc4AhHEGaETKtEdzc2rrm85IXszHhiTQRAlnfAlWMbYke22iwV4LU7i3QRs212cIXPmRTAV8XDFkB5wedNU6ekNQb1n7cLb5qqdDoUsKhdIPH79Is6BQrhv9PuOXF9B+yldGkjWOaWdTpnIeei53l7740eRPGoxoird4weSnHdsJo65c9jwvOkUvj3PkL+9YnGBlAAmVg0Ts80pCCsNRnJCs+t9ih83cw/88PUeqjah7QaNYahkG9AwIx9ghipcNp8g5cZlH71wHOjVEqumw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ns-dig
      namespace: cluster-tools
    type: Opaque

