apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ns-dig
  namespace: cluster-tools
spec:
  encryptedData:
    rfc2136_tsig_secret: AgBamgX9o7u1DgtqwFk2Eq1U0ni7GixfDOq00rYPZbQ9fL1IZ//47VEZN6fWy8tGh7TVObxzUMn5+THnX4+H25RWXbGbUR9p3joGEXik2ljxJ4W2wKyyxBvhAwL7ZL/cfjxP5ebdJUPfmriyURSh004yXXwOsQJheE+FOaME23COB1WWbqi/pOwVsndcrnAobxnT7+SvqPpxAFuW1c+zScbrk3KVOQEj8LrMeEfVXiJCrkqrWpwBSegGLV5Wznipm7JMYVAUVwtsrRq4GcqCkTIGJPsrzIPWbLUoMo2OFGppsplSF6bDW2Y1x3TiUdUGzYu3qq4n4symZq1qqzkJvvLgoW5/9uw6Au4/gN7s3Cxfd6YlzaktmvGCAPW1vmaSiAEy2QttFH801WU/owl1SeMJLFqoykvXrLMxHAuHuzCu5gWVUJtbK0cKjp8z3N3lOzoxrUea3HAoRkPxXqtKTp6OKsI1WvHJG/Koh9MHQDBQvLv/+cnwiJbgYvsKinR2DO3LuMMer0QsZ6GFnvPLFCVbl+EJJQaipsd6hZNThu97LLT9ZEI9YXFwUdP+M4j+iz4t+qGCYgO15X5SEm4sW2mSryL+x1csVPncKeOgVmYePDMKNXl6qDe7lBb8JHB1K/psy5eN2G3BKorA2eIrr7fjbaP3Tpt+yn+Fz+sy6YmxcFupPstFA1SthAiTwzhqNgfV1EstnKTJwN4f/dZ6+gTW4YjBjUp0GMaH2pJaUgGkP2XEhb2DBNDu4F1sEw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ns-dig
      namespace: cluster-tools
    type: Opaque

