apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-server
  namespace: tools-monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
             name: prometheus-operated
             port:
               number: 9090
      host: prometheus.staging.abhra.shambhala.cloud
  tls:
    - hosts:
      - prometheus.staging.abhra.shambhala.cloud
      secretName: prometheus-server-cert