apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-watcher-sa
  namespace: tools-argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-watcher-binding
  namespace: tools-argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events-watcher-role
subjects:
- kind: ServiceAccount
  name: argo-events-watcher-sa
  namespace: tools-argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-watcher-role
  namespace: tools-argo
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]