apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-all"
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
  - fromEndpoints:
    - {}
  egress:
  - fromEndpoints:
    - {}