apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: cd-tools
  annotations:
    argocd.argoproj.io/sync-wave: "80"
spec:
  nats:
    native:
      replicas: 3
      auth: token