
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts-as
  namespace: cd-tools
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: argo-rollouts
    spec:
      project: tools
      source:
        chart: argo-rollouts
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 2.17.0
        helm:
          releaseName: devopsdday
          values: |
            dashboard:
              enabled: true
              ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                  cert-manager.io/cluster-issuer: 'letsencrypt-{{metadata.labels.devopsdday/environment-type}}'
                  kubernetes.io/tls-acme: 'true'
                hosts: 
                  - rollouts.{{metadata.labels.devopsdday/url-base-path}}
                path: /
                pathType: Prefix
                tls: 
                  - secretName: argo-rollouts-server-cert
                    hosts:
                      - rollouts.{{metadata.labels.devopsdday/url-base-path}}
      destination:
        namespace: cd-tools
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
