apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-kaniko
  namespace: cd-tools
spec:
  templates:
    - name: kaniko-build-template
      volumes:
        - name: kaniko-secret
          secret:
            secretName: registry-secret
            items:
              - key: .dockerconfigjson
                path: config.json
      # inputs:
      #   parameters:
      #     - name: project_name
      container:
        image: gcr.io/kaniko-project/executor:debug
        command: [/bin/sh]
        # --destination=rg.fr-par.scw.cloud/weshare/test:{{workflow.parameters.commitId}} 
        args: 
          - "-c"
          - >-
            /kaniko/executor
            {{workflow.parameters.gitlabcontext}} 
            --context-sub-path=src/{{input.parameters.project_name}}
            --dockerfile=Dockerfile 
            --verbosity=debug
            --no-push
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        env:
          - name: GIT_USERNAME 
            valueFrom:
              secretKeyRef:
                name: gitlab-guru
                key: username
          - name: GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gitlab-guru
                key: token
      
