apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-watcher-sa
  namespace: cd-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-watcher-binding
  namespace: cd-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events-watcher-role
subjects:
- kind: ServiceAccount
  name: argo-events-watcher-sa
  namespace: cd-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-watcher-role
  namespace: cd-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]