apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sa
  namespace: cd-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-role-binding
  namespace: cd-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-role
subjects:
- kind: ServiceAccount
  name: argo-workflows-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-role
  namespace: cd-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - get