apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guru
  namespace: guru
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: guru
  source:
    repoURL: https://github.com/wescale/abhra-catherine
    targetRevision: HEAD
    path: guru
  destination:
    server: https://kubernetes.default.svc
    namespace: guru
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true