apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-server
  namespace: tools-monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
             name: abhra-grafana
             port:
               number: 80
      host: grafana.abhra.shambhala.cloud
  tls:
    - hosts:
      - grafana.abhra.shambhala.cloud
      secretName: grafana-server-cert