apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: k8s-event
spec:
  template:
    serviceAccountName: FIXME # assign a service account with `get`, `list` and `watch` permissions on the resource being watched.
  resource:
    argo-cd-secret:
      namespace: tools-argo-workflows
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - ADD
      filter:
        afterStart: false
        fields:
          - key: metadata.name
            operation: ==
            value: argo-cd-initial-admin-secret-workflow