apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: tools-argo-events
spec:
  nats:
    exotic:
      url: nats://abhra-nats-0.abhra-nats.tools-nats.svc.cluster.local:4222
      clusterID: nats
    #native:
      #replicas: 3 # optional, defaults to 3, and requires minimal 3
