apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: slack-sensor
  namespace: tools-argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: message-body
      eventSourceName: k8s-event
      eventName: argo-cd-secret
  triggers:
    - template:
        name: slack-trigger
        slack:
          channel: general
          message: hello world
          slackToken:
            key: token
            name: slack-secret
      parameters:
        - src:
            dependencyName: message-body
            dataKey: body.channel
          dest: slack.channel
        - src:
            dependencyName: message-body
            dataKey: body.message
          dest: slack.message