apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: tools-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: tools
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 37.0.0
    helm:
      releaseName: abhra
      skipCrds: true
      values: |
        grafana:
          #extraConfigmapMounts
          additionalDataSources:
            - name: Redis
              type: redis-datasource
              access: proxy
  destination:
    namespace: tools-monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true