apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ns-dig
  namespace: tools-external-dns
spec:
  encryptedData:
    rfc2136_tsig_secret: AgDDst2wfMEqXLavd7IORLgsFDF2LU1oOvEIdokyj6y1xYC4T3vOIchUwe5tGcy5RJdKuFcDxmBJurL7GaoViKikZCN9OSLmwkeX4Ws3uWhxuB4Dc5dXUM5xGQIRsiswyp2zN2NeFndQ/GkPL7KdqrxfPck2Dv+TCT12+pVQ3kKwVwiSGE+ajEKxLcylxA6sNhT1vv60q3oreBtTgJE4Marh3KSw4IFL5+iVLG4VEjAU/eQCbkqgVBRULGbv68EEMFjj/6NYOgBYwmNfVE6an8La19OkZnjOULnZV0TP8rs/dQPTk7tioWoNWJtr0dixRmMDSAtBR1zFvlSq8fGPBI0Kh+ztGO/dIK4qbi34j+u+Ez3GYYs2C2v0Zr2mOmeUdfpU58Fame7XGXYIXwo34B6clVl/XCg/HtkRicC2VHHBrsfPKiJhYEIsAX7lAjAWKWJ4c4L+5kD+DUZ3wV26Sre39B9V8xG7Z8my993MHaqWfYebt5IShqseq7g5X7xS72ruq4HQFY4/PAZGpKAf+RQAo2l7QTloBEKUKBJqbtP2dqcHKZvxxBapHsNNFs77AH1JBHJFfaWFthXDaaEMxuVCaA5/eFCw6K9YVpKZ9JPEHR9C8ZnHG8kImVcv1ncqE/qu/1uKE9JiNABAMnZTyjT/cR9IpCcjjsxu/nocMNxf0IwsLVo7DZiCxdwMyTq3VcIJG0H6J5kT7d5s+IGlXFYhDYh1ysNFOxXCagYwk8T3IHywZUeuFjLS3OcgbR4=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ns-dig
      namespace: tools-external-dns
    type: Opaque

