apiVersion: batch/v1
kind: Job
metadata:
  name: redis-loader
  namespace: guru
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: redis-loader
          image: rg.fr-par.scw.cloud/guru/redis-loader:latest
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password
          - name: REDIS_HOST
            value: "guru-redis-master"
          - name: REDIS_PORT
            value: "6379"
      restartPolicy: Never
  backoffLimit: 4
