apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-deployment
  namespace: cd-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: tools
  source:
    repoURL: https://github.com/wescale/abhra-catherine
    targetRevision: HEAD
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: cd-tools
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true