apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: tools-argo-cd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: cd.argo.abhra.shambhala.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: abhra-argocd-server
            port:
              name: https
