apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-server
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: https
    #cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
             name: argocd-server
             port:
               number: 443
      host: cd.argo.ingress.weshare.aws.wescale.fr
  tls:
    - hosts:
      - cd.argo.ingress.weshare.aws.wescale.fr
      secretName: argo-server-cert
