argo-cd:
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
    # envFrom: 
    # - secretRef:
    #     name: google-oidc-credentials
    url: https://cd-sso.argo.abhra.shambhala.cloud
    additionalProjects: 
      - name: tools
        namespace: tools-argo
        additionalAnnotations:
          app.kubernetes.io/managed-by : Helm
          meta.helm.sh/release-name: abhra
          meta.helm.sh/release-namespace: tools-argo
          argocd.argoproj.io/sync-wave: "4"
        finalizers:
        - resources-finalizer.argocd.argoproj.io
        description: Tooling project
        sourceRepos:
        - '*'
        destinations:
        - namespace: 'tools-*'
          server: https://kubernetes.default.svc
        - namespace: 'kube-system'
          server: https://kubernetes.default.svc
        clusterResourceWhitelist:
        - group: '*'
          kind: '*'
        namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    additionalApplications:
      - name: argocd
        namespace: tools-argo
        additionalAnnotations:
          app.kubernetes.io/managed-by : Helm
          meta.helm.sh/release-name: abhra
          meta.helm.sh/release-namespace: tools-argo
          argocd.argoproj.io/sync-wave: "2"
        destination:
          namespace: tools-argo
          server: https://kubernetes.default.svc
        project: tools
        source:
          helm:
            version: v3
            valueFiles:
            - values-patch.yaml
            releaseName: abhra
          path: argo-cd
          repoURL: https://github.com/wescale/abhra-catherine
          targetRevision: HEAD
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
      - name: tools
        namespace: tools-argo
        destination:
          namespace: tools-argo
          server: https://kubernetes.default.svc
        project: tools
        source:
          repoURL: https://github.com/wescale/abhra-catherine
          targetRevision: HEAD
          path: tools
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
    config:
      dex.config: |
        connectors:
        - config:
            issuer: https://accounts.google.com
            clientID: 757461153918-c53aktbh8crmarmu1b9fvuqi5i3aop3s.apps.googleusercontent.com
            clientSecret: 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
          type: oidc
          id: google
          name: Google
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: git
          url: https://github.com/wescale/abhra-catherine
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts: 
        - cd-sso.argo.abhra.shambhala.cloud
      pathType: Prefix
      tls: 
        - secretName: argocd-secret
          hosts:
            - cd-sso.argo.abhra.shambhala.cloud