apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guru-ingress-as
  namespace: tools-argo
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'guru-ingress'
    spec:
      project: tools
      source:
        repoURL: https://github.com/wescale/abhra-catherine
        targetRevision: HEAD
        path: tools/ingress/{{nameNormalized}}
      destination:
        server: https://kubernetes.default.svc
        namespace: tools-argo