apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: registry-secret
  namespace: guru
spec:
  encryptedData:
    .dockerconfigjson: AgC2ekB6GMsoX2442159FAYAGPAaDfWIE7QWwCy1R5Mh/vetP6JpHeNCPAGTLwoZ7NACklh608VRrG355vdNab9WZAqDIus699c+z4pwuKGOeBWFCU0wRYs8yEplELAHpOXuz7F0b/WQ7N03diOl3bB0c/ucz5LucBRzpBjpvVoamF7rriUIPdnYnrelPigQJ6CkKOOpmu/Tt2bC0/btO+XcGWpTFE9XZdsC/+hkjD4ZzqC5EymwAnRhzU8g5jDHeRnIISA++oZc7NdKNt66GafxmSbGSLlZXXMzhMc2Wm8e5aTBUVS3Th6uw48sta6iePyUpiu2t9d86gJ+/Wi/OiaB11+vCJJTVHah0mOp/nYEuuev1AUJit3w2rFO2KU06ADaVyAYLHq34pYU5QmFTinL2AIPssom3IxkBe+U2Yz87QCm9E1dAkgER7vNqsgTh5CmMgNPQher07CH9kHre8A5q3ab3KfkyKqZDaEAQUGcuFcqhp2tWM7wCdob7wk2m2U07ABggja/56s+obujLiotjDFqhhysbezPJV7tEpOoM8XreLh1smgMXX7JBTR12cEjJ6C4zMyxKgD3/a5lwTAhtKHul74iL9x+SY+o82TTWK3pjHTxpb5WD0kfMmRm1cVhdecp+tOBNN/nGesKS4gzOyoC7/vltKwzRzM+4qitxbxf2GDasBcTas+60dALkidwvn0jAoIyXvPzd4kmnV9qg766GAoBxq/1ZlEKUmzcBHHqDXYT0+REnsn0PXadr64quU+0S5GSg7lCzWypOM5LnjCniXTDIiC/R9Lwu2MOdKrSjD5rjvIO9hbc4BJd1yYiT6ULjYmOQ9xmazZENfWsek7KmYWo4+n8fNW2I7bDgtQkhph+a6NSSzPFpyYirHE+VmrOABLuenAtEVc0GeMCueR+SlJa4a6OQ4D+LLHS0Vlm5jBsay7J5fL8pEyG39TI9vcKafMQxBhFZXqlRJBdH/c=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: registry-secret
      namespace: guru
    type: kubernetes.io/dockerconfigjson

