argo-cd:
  server:
    config:
      url: https://cd.argo.staging.gitops.wescale.fr
    additionalApplications:
      - name: ingress
        namespace: cd-tools
        additionalAnnotations:
          argocd.argoproj.io/sync-wave: "30"
        destination:
          namespace: cluster-tools
          server: https://kubernetes.default.svc
        project: tools
        source:
          repoURL: https://github.com/plopez/devopsdday-gitops
          targetRevision: HEAD
          path: argo-apps/ingress
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
          - CreateNamespace=true
      - name: monitoring
        namespace: cd-tools
        additionalAnnotations:
          argocd.argoproj.io/sync-wave: "50"
        destination:
          namespace: cluster-tools
          server: https://kubernetes.default.svc
        project: tools
        source:
          repoURL: https://github.com/plopez/devopsdday-gitops
          targetRevision: HEAD
          path: argo-apps/monitoring
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
          - CreateNamespace=true
      - name: cicd
        namespace: cd-tools
        additionalAnnotations:
          argocd.argoproj.io/sync-wave: "100"
        destination:
          namespace: cluster-tools
          server: https://kubernetes.default.svc
        project: tools
        source:
          repoURL: https://github.com/plopez/devopsdday-gitops
          targetRevision: HEAD
          path: argo-apps/cicd
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
          - CreateNamespace=true
      # - name: guru
      #   namespace: cd-tools
      #   additionalAnnotations:
      #     argocd.argoproj.io/sync-wave: "200"
      #   destination:
      #     namespace: cluster-tools
      #     server: https://kubernetes.default.svc
      #   project: tools
      #   source:
      #     repoURL: https://gitlab.com/abhra-shambhala/guru.git
      #     targetRevision: staging
      #     path: argo-apps
      #   syncPolicy:
      #     automated:
      #       selfHeal: true
      #       prune: true
      #     syncOptions:
      #     - CreateNamespace=true
