argo-cd:
  dex:
    enabled: true
  server:
    rbacConfig:
      policy.default: role:admin
    extraArgs:
      - --insecure
    config:
      url: https://cd.argo.abhra.shambhala.cloud
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: git
          url: https://github.com/wescale/abhra-catherine
      dex.config: |
        connectors:
        - config:
            issuer: https://accounts.google.com
            clientID: $google-secret:clientID
            clientSecret: $google-secret:clientSecret
          type: oidc
          id: google
          name: Google
