argo-cd:
  dex:
    enabled: true
  server:
    additionalProjects: 
      - name: tools
        namespace: cd-tools
        additionalAnnotations:
          app.kubernetes.io/managed-by : Helm
          meta.helm.sh/release-name: devopsdday
          meta.helm.sh/release-namespace: cd-tools
        finalizers:
        - resources-finalizer.argocd.argoproj.io
        description: Tooling project
        sourceRepos:
        - '*'
        destinations:
        - namespace: '*-tools'
          server: https://kubernetes.default.svc
        - namespace: 'kube-system'
          server: https://kubernetes.default.svc
        clusterResourceWhitelist:
        - group: '*'
          kind: '*'
        namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    additionalApplications:
      - name: ingress
        namespace: cd-tools
        additionalAnnotations:
          argocd.argoproj.io/sync-wave: "30"
        destination:
          namespace: cluster-tools
          server: https://kubernetes.default.svc
        project: tools
        source:
          repoURL: https://github.com/plopez/devopsdday-gitops
          targetRevision: HEAD
          path: argo-apps/ingress
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
          - CreateNamespace=true
      - name: monitoring
        namespace: cd-tools
        additionalAnnotations:
          argocd.argoproj.io/sync-wave: "50"
        destination:
          namespace: cluster-tools
          server: https://kubernetes.default.svc
        project: tools
        source:
          repoURL: https://github.com/plopez/devopsdday-gitops
          targetRevision: HEAD
          path: argo-apps/monitoring
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
          - CreateNamespace=true
      - name: cicd
        namespace: cd-tools
        additionalAnnotations:
          argocd.argoproj.io/sync-wave: "100"
        destination:
          namespace: cluster-tools
          server: https://kubernetes.default.svc
        project: tools
        source:
          repoURL: https://github.com/plopez/devopsdday-gitops
          targetRevision: HEAD
          path: argo-apps/cicd
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
          - CreateNamespace=true
      - name: app
        namespace: cd-tools
        additionalAnnotations:
          argocd.argoproj.io/sync-wave: "200"
        destination:
          namespace: cluster-tools
          server: https://kubernetes.default.svc
        project: tools
        source:
          repoURL: https://gitlab.com/abhra-shambhala/guru.git
          targetRevision: stadium
          path: argo-apps
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
          - CreateNamespace=true
    rbacConfig:
      policy.default: role:admin
    extraArgs:
      - --insecure
    config:
      url: https://cd.argo.gitops.wescale.fr
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: git
          url: https://github.com/plopez/devopsdday-gitops
        - type: git
          url: https://gitlab.com/abhra-shambhala/guru.git
          passwordSecret:
            name: gitlab-guru
            key: token
          usernameSecret:
            name: gitlab-guru
            key: username
        - type: helm
          name: guru-stable
          url: https://gitlab.com/api/v4/projects/abhra-shambhala%2Fguru/packages/helm/stable
          passwordSecret:
            name: gitlab-guru
            key: token
          usernameSecret:
            name: gitlab-guru
            key: username
      dex.config: |
        connectors:
        - config:
            issuer: https://accounts.google.com
            clientID: $google-secret:clientID
            clientSecret: $google-secret:clientSecret
          type: oidc
          id: google
          name: Google
