apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-runner-kube
  # Ongoing bug : https://github.com/argoproj/argo-cd/issues/3474
  namespace: tools-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: guru
  source:
    chart: drone-runner-kube
    repoURL: https://charts.drone.io
    targetRevision: 0.1.9
    helm:
      releaseName: guru
      values: |
        # imagePullSecrets:
        #   - name: registry-secret
        rbac:
          buildNamespaces:
            - guru
        env:
          DRONE_NAMESPACE_DEFAULT: guru
          # KUBERNETES_NAMESPACE: guru
          DRONE_RPC_HOST: guru-drone
          DRONE_TRACE: true
          DRONE_DEBUG: true
          DRONE_RPC_DUMP_HTTP: true
          DRONE_RPC_DUMP_HTTP_BODY: true
        extraSecretNamesForEnvFrom:
          - drone-runner-kube-secrets
          - drone-secrets
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - host: drone-runner.abhra.shambhala.cloud
              paths:
                - "/"
                pathType: Prefix
  destination:
    namespace: guru
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

