apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-sa
  namespace: guru
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drone-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drone-role
subjects:
- kind: ServiceAccount
  name: drone-sa
  namespace: guru
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drone-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "configmaps", "namespaces"]
  verbs: ["create", "delete", "list", "get"]