apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: tools-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: tools
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.16.6
    helm:
      releaseName: abhra
      values: |
        workflow:
          rbac:
            create: false
          serviceAccount:
            name: argo-workflow-sa
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: 'letsencrypt-production'
              kubernetes.io/tls-acme: 'true'
            hosts: 
              - workflows.argo.abhra.shambhala.cloud
            path: /
            pathType: Prefix
            tls: 
              - secretName: argo-workflows-server-cert
                hosts:
                  - workflows.argo.abhra.shambhala.cloud
  destination:
    namespace: tools-argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

