apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: tools-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: tools
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.17.0
    helm:
      releaseName: abhra
      values: |
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: 'letsencrypt-production'
              kubernetes.io/tls-acme: 'true'
            hosts: 
              - rollout.argo.abhra.shambhala.cloud
            path: /
            pathType: Prefix
            tls: 
              - secretName: argo-rollout-server-cert
                hosts:
                  - rollout.argo.abhra.shambhala.cloud
  destination:
    namespace: tools-argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

