apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: tools-argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tools
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.8.2
    helm:
      releaseName: abhra
      value: |
          installCRDs: true
  destination:
    namespace: tools-cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

