apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools
  namespace: tools-argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tools
  source:
    repoURL: https://github.com/wescale/abhra-catherine
    targetRevision: HEAD
    path: issuers
  destination:
    server: https://kubernetes.default.svc
    #namespace: tools-definitions
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true