apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: tools-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: tools
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 37.0.0
    helm:
      releaseName: abhra
      skipCrds: true
      values: |
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: 'letsencrypt-production'
              kubernetes.io/tls-acme: 'true'
            hosts: 
              - prometheus.abhra.shambhala.cloud
            path: /
            pathType: Prefix
            tls: 
              - secretName: prometheus-server-cert
                hosts:
                  - prometheus.abhra.shambhala.cloud
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: 'letsencrypt-production'
              kubernetes.io/tls-acme: 'true'
            hosts: 
              - grafana.abhra.shambhala.cloud
            path: /
            pathType: Prefix
            tls: 
              - secretName: grafana-server-cert
                hosts:
                  - grafana.abhra.shambhala.cloud
              

  destination:
    namespace: tools-monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true