apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: tools-argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: tools
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.13.1
    helm:
      releaseName: abhra
  destination:
    namespace: tools-loki
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

