apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: tools-argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: tools
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.10.4
    helm:
      releaseName: abhra
      values: |
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              kubernetes.io/ingress.class: 'nginx'
              cert-manager.io/cluster-issuer: 'letsencrypt-production'
              kubernetes.io/tls-acme: 'true'
            hosts: 
              - prometheus.abhra.shambhala.cloud
            path: /
            pathType: Prefix
            tls: 
              - secretName: prometheus-server-cert
                hosts:
                  - prometheus.abhra.shambhala.cloud
              

  destination:
    namespace: tools-prometheus
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true