apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-deployments
  namespace: tools-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: tools
  source:
    repoURL: https://github.com/wescale/abhra-catherine
    targetRevision: HEAD
    path: resources/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: tools-argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true