---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tools
  namespace: tools-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Tooling project
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'tools-*'
    server: https://kubernetes.default.svc
  - namespace: 'kube-system'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
