---
- hosts: "localhost"
  become: false
  gather_facts: false
  strategy: linear

  vars:
    tooling_namespace: "cd-tools"

    sealed_secret_helm_deploy_name: "abhra"
    sealed_secret_chart_path: "{{ project_root }}/helm/sealed-secrets"
    sealed_secret_master_key_path: "{{ project_root }}/secrets/master.key"
    sealed_secret_google_sso_path: "{{ project_root }}/resources/sealed-secrets/google-secret.yaml"

    argocd_helm_deploy_name: "abhra"
    argocd_chart_path: "{{ project_root }}/helm/argo-cd"

  tasks:
    - name: "Create tooling namespace"
      kubernetes.core.k8s:
        name: "{{ tooling_namespace }}"
        kind: Namespace
        state: present

    - name: "Install sealed-secret master key"
      kubernetes.core.k8s:
        namespace: "{{ tooling_namespace }}"
        src: "{{ sealed_secret_master_key_path }}"
        state: present

    - name: "Install sealed-secret engine"
      kubernetes.core.helm:
        release_namespace: "{{ tooling_namespace }}"
        name: "{{ sealed_secret_helm_deploy_name }}"
        chart_ref: "{{ sealed_secret_chart_path }}"
        wait: true
        replace: true

    - name: "Deploy Google SSO values for argo-cd authentication"
      kubernetes.core.k8s:
        namespace: "{{ tooling_namespace }}"
        src: "{{ sealed_secret_google_sso_path }}"
        state: present

    - name: "Install argo-cd"
      kubernetes.core.helm:
        release_namespace: "{{ tooling_namespace }}"
        name: "{{ argocd_helm_deploy_name }}"
        chart_ref: "{{ argocd_chart_path }}"
        wait: true
        replace: true
